# Generated by Django 5.1.4 on 2024-12-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterapp', '0003_category_users_category_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
